name: Build pyinstaller bins

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install ffmpeg
        shell: powershell
        run: |
          winget install "FFmpeg (Essentials Build)"
          $ffmpegPath = (Get-Command ffmpeg).Path
          $ffmpegDir = Split-Path -Parent $ffmpegPath
          
          mkdir ffmpeg_binaries
          Copy-Item "$ffmpegDir\ffmpeg.exe" "ffmpeg_binaries/"
          Copy-Item "$ffmpegDir\ffprobe.exe" "ffmpeg_binaries/"
          Copy-Item "$ffmpegDir\ffplay.exe" "ffmpeg_binaries/"
          

      - name: build exe
        shell: powershell
        run: |
          pip install pip -U
          pip install -r requirements.txt
          pyinstaller --onefile --add-binary "ffmpeg_binaries/ffmpeg.exe;," --add-binary "ffmpeg_binaries/ffprobe.exe;," --add-binary "ffmpeg_binaries/ffplay.exe;," --windowed --name yt_dlp_gui main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt_dlp_gui.exe
          path: .\dist\yt_dlp_gui.exe

  publish:
    runs-on: ubuntu-latest
    needs: build_exe
    permissions:
      contents: write
    steps:
      - name: Download exe
        uses: actions/download-artifact@v3
        with:
          name: yt_dlp_gui.exe
          path: /tmp

      - name: Generate Prerelease Release Notes
        run: |
          zip /tmp/yt_dlp_gui_windows.zip /tmp/yt_dlp_gui.exe && rm /tmp/yt_dlp_gui.exe || ls /tmp
          echo '### yt_dlp_gui `latest`' >> ReleaseNotes.md
          

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "ReleaseNotes.md"
          artifacts: /tmp/yt_dlp_gui*.*
          tag: "v1.0.1"
          token: ${{ secrets.GITHUB_TOKEN }}

