name: Build fbs bins

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      - name: build exe
        shell: powershell
        run: |
          pip install pip -U
          pip install -r requirements.txt
          fbs freeze
          fbs installer

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt_dlp_gui_setup.exe
          path: .\target\yt_dlp_gui_setup.exe

  publish:
    runs-on: ubuntu-latest
    needs: build_exe
    steps:
      - name: Download exe
        uses: actions/download-artifact@v3
        with:
          name: yt_dlp_gui_setup.exe
          path: /tmp

      - name: Generate Prerelease Release Notes
        run: |
          zip /tmp/yt_dlp_gui_windows.zip /tmp/yt_dlp_gui_setup.exe && rm /tmp/yt_dlp_gui_setup.exe || ls /tmp
          echo '### yt_dlp_gui `latest`' >> ReleaseNotes.md
          

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "ReleaseNotes.md"
          artifacts: /tmp/yt_dlp_gui*.*
          tag: "v1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

