name: Build pyinstaller bins

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install ffmpeg
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip" -OutFile "ffmpeg-release-essentials.zip"
          Expand-Archive "ffmpeg-release-essentials.zip"

      - name: build exe
        shell: powershell
        run: |
          pip install pip -U
          pip install -r requirements.txt
          
          $ffmpegDir = Get-ChildItem -Path "./ffmpeg-release-essentials" -Directory | Where-Object { $_.Name -match "ffmpeg-.*-essentials_build" }
          $ffmpegBinDir = Join-Path $ffmpegDir.FullName "bin"
          echo "ffmpeg bin dir: $ffmpegBinDir"
          
          pyinstaller --onefile `
          --add-binary "$ffmpegBinDir\ffmpeg.exe;," `
          --add-binary "$ffmpegBinDir\ffprobe.exe;," `
          --add-binary "$ffmpegBinDir\ffplay.exe;," `
          --windowed --name yt_dlp_gui main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt_dlp_gui.exe
          path: .\dist\yt_dlp_gui.exe

  publish:
    runs-on: ubuntu-latest
    needs: build_exe
    permissions:
      contents: write
    env:
      VERSION: 1.0.1
      APP_NAME: yt_dlp_gui
      TMP_DIR: "${{ github.workspace }}/$APP_NAME_$VERSION/"
    steps:
      - name: Create temp dir
        run: |
          mkdir -p $TMP_DIR/$APP_NAME

      - name: Download exe
        uses: actions/download-artifact@v3
        with:
          name: yt_dlp_gui.exe
          path: $TMP_DIR/$APP_NAME

      - name: Generate Prerelease Release Notes
        run: |
          zip -r "$APP_NAME_$VERSION.zip" -j $TMP_DIR. && rm $TMP_DIR
          echo '### $APP_NAME `latest`' >> ReleaseNotes.md

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "ReleaseNotes.md"
          artifacts: "$APP_NAME_$VERSION.zip"
          tag: "v$VERSION"
          token: ${{ secrets.GITHUB_TOKEN }}

